version: '3.9'

services:
  hrms.sql:
    container_name: HRMS.SQL
    build:
      context: .
      dockerfile: HRMS.Database/Dockerfile
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${SQL_PASSWORD}
      - MSSQL_PID=${SQL_PID}
      - MSSQL_AGENT_ENABLED=true
    ports:
      - ${SQL_PORT}:1433

  hrms.rabbitmq:
    container_name: HRMS.RabbitMQ
    image: rabbitmq:3.12.1-management
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=${RMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RMQ_PASSWORD}
    ports:
      - ${RMQ_PORT}:5672
      - ${RMQ_ADMIN_PORT}:15672

  hrms.identityserver:
    container_name: HRMS.IdentityServer
    build:
      context: .
      dockerfile: HRMS.IdentityServer/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORT=${IS_HTTPS_PORT}
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Pass@*****
      - ASPNETCORE_Kestrel__Certificates__Default__Path=certificate.pfx
      - ConnectionStrings:HRMS_Database=Server=hrms.sql,1433;Database=${SQL_DATABASE};Trusted_Connection=False;Encrypt=False;User=${SQL_USER};Password=${SQL_PASSWORD};
      - JWTSecret=${IS_JWT_SECRET}
    ports:
      - ${IS_PORT}:80
      - ${IS_HTTPS_PORT}:443
    depends_on:
      - hrms.sql

  hrms.api:
    container_name: HRMS.API
    build:
      context: .
      dockerfile: HRMS/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORT=${API_HTTPS_PORT}
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Pass@*****
      - ASPNETCORE_Kestrel__Certificates__Default__Path=certificate.pfx
      - ConnectionStrings:HRMS_Database=Server=hrms.sql,1433;Database=${SQL_DATABASE};Trusted_Connection=False;Encrypt=False;User=${SQL_USER};Password=${SQL_PASSWORD};
      - HangfireKey=${HANGFIRE_KEY}
      - IdentityServerUrl=https://hrms.identityserver
      - IdentityServerMetaDataUrl=http://hrms.identityserver/.well-known/openid-configuration
      - IdentityServerJWTSecret=${IS_JWT_SECRET}
      - RabbitMQ:Host=hrms.rabbitmq
      - RabbitMQ:Port=${RMQ_PORT}
      - RabbitMQ:User=${RMQ_USER}
      - RabbitMQ:Password=${RMQ_PASSWORD}
    ports:
      - ${API_PORT}:80
      - ${API_HTTPS_PORT}:443
    depends_on:
      - hrms.sql
      - hrms.rabbitmq
      - hrms.identityserver